apiVersion: v1
kind: Service
metadata:
  name: test-databroker1webui
spec:
  ports:
  - name: webui
    nodePort: 30003
    port: 30003
    targetPort: 8062
  selector:
    app: test-databroker1
  type: NodePort
