apiVersion: v1
kind: Service
metadata:
  name: test-databroker1
spec:
  ports:
  - name: protobuf-api
    nodePort: 30002
    port: 30002
    targetPort: 8061
  selector:
    app: test-databroker1
  type: NodePort
