apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-model1
  name: test-model1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-model1
  template:
    metadata:
      labels:
        app: test-model1
    spec:
      containers:
      - image: hub.docker.com/rafluq/test_model:v4
        imagePullPolicy: Always
        name: test-model1
        ports:
        - containerPort: 8061
          name: protobuf-api
        - containerPort: 8062
          name: webui
      imagePullSecrets:
      - name: acumos-registry
